# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  omniauth_provider_key: 791850004245509
  omniauth_provider_secret: b8bf1f00d21ab5d4c17ee9586c00a76c
  domain_name: localhost:3000
  secret_key_base: 13214af9e26cc1ab04a059e8ec7c1da9d679a7dff95aebb5269acadb583dc68e2c565049be8831135d5c0b4c3f529d891db3738e0fa59d92c7b9d7e474498363

test:
  secret_key_base: 84cf3cc17b02ffc9bc436977f2a954135003a261d50b38f0f285578790f11f7155ca481abd439a5f2d8b035d07655f74bcd079c0ce8f9d31353ec9c7da580cee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  omniauth_provider_key: <%= ENV["OMNIAUTH_PROVIDER_KEY"] %>
  omniauth_provider_secret: <%= ENV["OMNIAUTH_PROVIDER_SECRET"] %> 
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
